bats fixes

diff --git a/tests/lib/config/config-global b/tests/lib/config/config-global
--- a/tests/lib/config/config-global
+++ b/tests/lib/config/config-global
@@ -46,14 +46,14 @@ else
 fi
 
 remove_init_data() {
-    ./bin/assert-crowdsec-not-running
+    ./bin/assert-crowdsec-not-running || die "Cannot remove fixture data."
     rm -rf -- "${LOCAL_DIR:?}/${REL_CONFIG_DIR}"/* "${LOCAL_DIR:?}/${REL_DATA_DIR:?}"/*
 }
 
 # we need a separate function for initializing config when testing package
 # because we want to test the configuration as well
 make_init_data() {
-    ./bin/assert-crowdsec-not-running
+    ./bin/assert-crowdsec-not-running || die "Cannot create fixture data."
 
     ./instance-db config-yaml
     ./instance-db setup
@@ -78,7 +78,7 @@ make_init_data() {
 }
 
 load_init_data() {
-    ./bin/assert-crowdsec-not-running
+    ./bin/assert-crowdsec-not-running || die "Cannot load fixture data."
 
     if [[ ! -f "${LOCAL_INIT_DIR}/init-config-data.tar" ]]; then
         die "Initial data not found; did you run '${script_name} make' ?"
