cscli machines: lint + write output to stdout instead of log (#2657)
* feedback on stdout, not log.Info
* rename parameters to silence warnings from "unusedparams"
* debian postinst: skip duplicate warnings with 'cscli machines add'
* rpm postinst: skip duplicate warnings in 'cscli machines add'
* update func tests
* debian prerm: if dashboard remove fails, explain it's ok
* debian prerm: suppress warnings about wal, capi when attempting to remove the dashboard
* wizard.sh: log format like crowdsec

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,5 +1,5 @@
 if [ "$1" = "remove" ]; then
-   cscli dashboard remove -f -y || true
+   cscli dashboard remove -f -y --error || echo "Ignore the above error if you never installed the local dashboard."
    systemctl stop crowdsec
    systemctl disable crowdsec
 fi
