grouping to make it better

diff --git a/.github/workflows/hub-ci.yml b/.github/workflows/hub-ci.yml
--- a/.github/workflows/hub-ci.yml
+++ b/.github/workflows/hub-ci.yml
@@ -31,8 +31,8 @@ jobs:
     - name: Run the tests
       working-directory: crowdsec-pull/tests/
       run: |
-      for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
-        echo "::group::Test-${i}" ; 
-        ./main $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail") ;
-        echo "::endgroup::" ;
-      done 
+        for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
+          echo "::group::Test-${i}" ; 
+          ./main $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.yaml" ${i}"/results.yaml.fail") ;
+          echo "::endgroup::" ;
+        done ;
