debug

diff --git a/.github/workflows/hub_tests.yml b/.github/workflows/hub_tests.yml
--- a/.github/workflows/hub_tests.yml
+++ b/.github/workflows/hub_tests.yml
@@ -53,5 +53,10 @@ jobs:
         cp -R ../../hub-tests/tests .
         cp ../../hub-tests/main .
     - name: Run the HUB CI
-      working-directory: ./crowdsec-${{ steps.crowdsec.outputs.tag }}/tests/
-      run: ls -lR .
+      working-directory: ./crowdsec-${{ steps.keydb.outputs.release }}/tests/
+      run: |
+        for i in `find ./tests -mindepth 1 -maxdepth 1 -type d` ; do 
+          echo "::group::Test-${i}" ; 
+          ./main -c dev.yaml $i || (echo "::error file=${i}::Failed test for ${i}" ; diff ${i}"/results.json" ${i}"/results.json.fail") ;
+          echo "::endgroup::" ;
+        done ;
